"""Kétnyelvű szövegek a szakértői kérdőívhez (magyar és angol).

A magyar a kanonikus változat; az angol a külföldi kollégáknak. A tételek
kódjai és a válaszkódok nyelvfüggetlenek, csak a megjelenített szöveg változik.
"""

LANGS = ("hu", "en")
# A kitöltő szerepe: fogorvos (alapértelmezés) vagy fogtechnikus. Ugyanaz az
# űrlap, minden tétel mindkettőnek megjelenik; a háttérkérdések és néhány
# megfogalmazás a szerephez igazodik (ROLE_UI), az elemzés szerep szerint bont.
ROLES = ("fogorvos", "fogtechnikus")
ROLE_LABELS = {
    "hu": {"fogorvos": "fogorvos", "fogtechnikus": "fogtechnikus"},
    "en": {"fogorvos": "dentist", "fogtechnikus": "dental technician"},
}

# A PREDICT mozaikszó feloldása; a meghívólevélben egyszer, az első említésnél
# jelenik meg (a vizsgálatvezető által megadott hivatalos cím).
STUDY_ACRONYM = {
    "hu": ("Prognostic evaluation of the edentulous: inspecting critical anatomy, azaz a fogatlan páciens prognosztikai "
           "értékelése a meghatározó anatómiai adottságok vizsgálatával"),
    "en": "Prognostic evaluation of the edentulous: inspecting critical anatomy",
}

JAW_LABELS = {
    "hu": {"Felső állcsont": "Felső állcsont", "Alsó állcsont": "Alsó állcsont"},
    "en": {"Felső állcsont": "Upper jaw", "Alsó állcsont": "Lower jaw"},
}

IRANY_LABELS = {
    "hu": {
        "A_kedvezotlenebb": "az A változat a rosszabb",
        "B_kedvezotlenebb": "a B változat a rosszabb",
        "nem_monoton": "a közepes a legjobb, a két véglet rosszabb",
        "nincs_kulonbseg": "nincs érdemi különbség",
        "nem_tudom": "nem tudom megítélni",
    },
    "en": {
        "A_kedvezotlenebb": "variant A is worse",
        "B_kedvezotlenebb": "variant B is worse",
        "nem_monoton": "the middle is best, both extremes are worse",
        "nincs_kulonbseg": "no real difference",
        "nem_tudom": "cannot judge",
    },
}

# Az angol tételszövegek kódonként; a magyar a regiszterben (expert_priors.ITEMS).
ITEM_TEXT_EN = {
    "F1": {
        "nev": "Height of the upper ridge",
        "rogzit": "On the plaster cast we measure how high the upper alveolar ridge is.",
        "A": "high, well-preserved ridge (about 10 mm on the cast)", "B": "low, resorbed ridge",
        "kuszob": "Below what height would you call the upper ridge low? (mm)",
        "B": "low, resorbed ridge (about 5 mm on the cast)",
    },
    "F2": {
        "nev": "Undercut areas of the upper jaw",
        "rogzit": "On the cast we measure how much undercut area the upper jaw has.",
        "A": "little or hardly any undercut", "B": "large undercut",
        "kuszob": "If a moderate amount is best: roughly what amount of undercut is ideal? (a few words)",
        "M": "moderate undercut",
        "B": "large, pronounced undercut",
    },
    "F3": {
        "nev": "Height of the palate",
        "rogzit": "On the cast we measure the height of the palatal vault.",
        "A": "high, vaulted palate (about 25 mm)", "B": "flat palate",
        "kuszob": "Below what height would you call the palate flat? (mm)",
        "B": "flat palate (about 17 mm)",
    },
    "F4": {
        "nev": "Shape of the upper ridge arch",
        "rogzit": "On the cast we measure the arch angle: a larger angle means a squarer arch, a smaller one a tapered, V-shaped arch.",
        "A": "square, wide arch (about 140°)", "B": "tapered, V-shaped arch",
        "kuszob": "Is there an angle above which there is no further benefit? (°)",
        "B": "tapering, V-shaped arch (about 125°)",
    },
    "F5": {
        "nev": "Flabby ridge in the upper jaw",
        "rogzit": "At the examination we note: none; flabby tuberosities; flabby anterior ridge.",
        "A": "no flabby ridge", "B": "flabby ridge present",
        "subs": {"lokalizacio": {"kerdes": "If present: which is worse?",
                                 "opciok": {"frontalis": "on the anterior ridge", "tuberalis": "on the tuberosities", "egyforma": "the same", "nem_tudom": "don't know"}}},
    },
    "F6": {
        "nev": "Position of the upper and lower ridge crests relative to each other",
        "rogzit": "On the cast we measure whether the upper and lower ridge crests lie vertically above each other (90°) or deviate from each other.",
        "A": "the two ridge crests are above each other (deviation at most 5°)", "B": "the two crests deviate considerably",
        "kuszob": "How large a deviation would you already consider significant? (°)",
        "subs": {"irany_szamit": {"kerdes": "Does the direction of the deviation matter (lower arch wider, or upper arch wider)?",
                                  "opciok": {"igen": "yes", "nem": "no", "nem_tudom": "don't know"}}},
        "M": "moderate deviation (about 10°)",
        "B": "large deviation (20° or more)",
    },
    "F7": {
        "nev": "Torus palatinus",
        "rogzit": "At the examination we note: none; flat (plateau-shaped); spindle-shaped.",
        "A": "no torus", "B": "torus present (flat or spindle-shaped)",
        "subs": {"alak_rosszabb": {"kerdes": "If present: which shape is worse?",
                                   "opciok": {"orso": "the spindle-shaped", "plato": "the flat one", "egyforma": "the same", "nem_tudom": "don't know"}}},
    },
    "F8": {
        "nev": "What opposes the upper denture (antagonist)",
        "rogzit": "At the examination we note: none, being made now; removable denture (complete denture, overdenture, metal-framework partial); retained natural teeth or fixed restoration.",
        "A": "removable denture in the opposing jaw", "B": "retained natural teeth or fixed restoration",
        "subs": {"kategoria_vagy_interakcio": {"kerdes": "Do you think the type of antagonist itself matters, or rather the direction of the forces (for example a forced scissor bite on a resorbed upper jaw)?",
                                               "opciok": {"kategoria": "the type of antagonist", "interakcio": "the direction of the forces", "mindketto": "both", "nem_tudom": "don't know"}}},
    },
    "A1": {
        "nev": "Shape and height of the lower ridge (Kaán classification)",
        "rogzit": "At the examination we grade the lower ridge in five classes: (1) preserved throughout; (2) preserved anteriorly, flat laterally; (3) flat throughout; (4) negative; (5) deepened negative. On the cast we also measure the ridge height.",
        "A": "ridge preserved throughout (1)", "B": "deepened negative ridge (5)",
        "kuszob": "Below what height would you call the lower ridge resorbed? (mm)",
        "subs": {
            "legnagyobb_ugras": {"kerdes": "Between which two classes does the outlook worsen the most?",
                                 "opciok": {"1_2": "between 1 and 2", "2_3": "between 2 and 3", "3_4": "between 3 and 4", "4_5": "between 4 and 5", "egyenletes": "roughly evenly"}},
            "negy_ot_kulonbseg": {"kerdes": "Is there a real difference between a negative and a deepened negative ridge?",
                                  "opciok": {"igen": "yes", "nem": "no", "nem_tudom": "don't know"}},
        },
    },
    "A3": {
        "nev": "The buccinator pouch",
        "rogzit": "At the examination we note what the pouch does on mouth opening: it narrows; it widens; or its surface is lobulated.",
        "A": "pouch that narrows on opening", "B": "pouch that widens on opening",
        "subs": {"lebenyezett": {"kerdes": "And the lobulated pouch?",
                                 "opciok": {"legkedvezobb": "that is the best", "koztes": "in between", "legkedvezotlenebb": "that is the worst", "nem_tudom": "don't know"}}},
    },
    "A4": {
        "nev": "Torus mandibularis",
        "rogzit": "At the examination we note on both sides: none; small; large.",
        "A": "no torus", "B": "torus present (small or large)",
        "subs": {"nagy_vs_kicsi": {"kerdes": "If present: how much worse is a large torus than a small one?",
                                   "opciok": {"alig": "hardly", "kozepesen": "moderately", "sokkal": "much", "nem_tudom": "don't know"}}},
    },
    "A5": {
        "nev": "The lingual pouch during swallowing",
        "rogzit": "At the examination we place a finger in the pouch and the patient swallows: the muscles press the finger against the jaw; they do not narrow the pouch; or they push the finger outwards.",
        "A": "the muscles press the finger against the jaw", "B": "the muscles push the finger outwards",
        "subs": {"nem_szukit_helye": {"kerdes": "And if the muscles do not narrow the pouch?",
                                      "opciok": {"A_kozel": "that is closer to A", "kozepen": "in between", "B_kozel": "that is closer to B", "nem_tudom": "don't know"}}},
    },
    "TUB": {
        "nev": "The retromolar pad (tuberculum alveolare mandibulae)",
        "rogzit": "We look at four things: whether attached gingiva covers it; its shape (pear-shaped, small, fold-like); its inclination to the ridge; whether it moves on mouth opening.",
        "A": "covered by attached gingiva, well shaped, immobile", "B": "uncovered, fold-like, mobile",
        "subs": {"legfontosabb": {"kerdes": "Which of the four matters most?",
                                  "opciok": {"A6": "the attached gingiva cover", "A7": "its shape", "A8": "its inclination", "A9": "whether it moves", "nem_tudom": "don't know"}}},
    },
    "A10": {
        "nev": "Sagittal relation of the jaws",
        "rogzit": "On the cast we measure whether the lower jaw sits further forward or further back relative to the upper jaw; essentially the Angle class.",
        "A": "Angle Class I, normal relation", "B": "Angle Class II or III, deviating relation",
        "subs": {"melyik_rosszabb": {"kerdes": "If a deviation is bad: which is worse?",
                                     "opciok": {"angle_II": "Angle Class II", "angle_III": "Angle Class III", "egyforma": "the same", "nem_tudom": "don't know"}}},
    },
    "A11": {
        "nev": "The floor of the mouth",
        "rogzit": "At the examination we note: not bulging; softly bulging; firm and bulging.",
        "A": "softly bulging floor of the mouth", "B": "firm, bulging floor of the mouth",
        "subs": {"nem_elodomborodo_helye": {"kerdes": "And the non-bulging floor of the mouth?",
                                            "opciok": {"A_kozel": "that is closer to A", "kozepen": "in between", "B_kozel": "that is closer to B", "nem_tudom": "don't know"}}},
    },
    "A12": {
        "nev": "Genial tubercles (spinae mentales)",
        "rogzit": "At the examination we note: not palpable; palpable; tender to pressure.",
        "A": "not palpable", "B": "palpable or tender to pressure",
        "subs": {"erzekeny_vs_tapinthato": {"kerdes": "If palpable: how much worse is it when it is also tender to pressure?",
                                            "opciok": {"alig": "hardly", "kozepesen": "moderately", "sokkal": "much", "nem_tudom": "don't know"}}},
    },
}

UI = {
    "hu": {
        "brand_small": "szakértői kérdőív",
        "role_q": "Milyen minőségben tölti ki? *",
        "role_opts": [("fogorvos", "fogorvosként"), ("fogtechnikus", "fogtechnikusként")],
        "footer_line": "Semmelweis Egyetem · Fogpótlástani Klinika · PREDICT-vizsgálat",
        "prep_title": "Felkészítő · PREDICT szakértői kérdőív",
        "prep_eyebrow": "Felkészítő · körülbelül 5 perc",
        "prep_h1": "Mielőtt elkezdené: hogyan adjunk számot arról, amiben nem vagyunk biztosak?",
        "prep_lead": "A kérdőív szokatlan dolgot kér: számokat olyan dolgokról, amelyeket senki sem tud pontosan. Ez a rövid felkészítő és a három gyakorlókérdés abban segít, hogy a számai azt jelentsék, amit gondol. A gyakorlókérdések válaszait nem értékeljük, csak Önnek adnak visszajelzést.",
        "prep_1_h3": "Kétféle bizonytalanság van, és a kettőt külön kérdezzük",
        "prep_1_p": "Az egyik a betegek közötti különbség: száz betegből nem mindenkinek lesz sikeres a fogsora, akkor sem, ha az adottságaik egyformák. Ezt a „száz betegből hány” szám fejezi ki. A másik az Ön tudásának bizonytalansága: nem tudhatja pontosan, hogy ez a szám 60 vagy 75. Ezt az alsó és felső határ fejezi ki. A két dolog nem ugyanaz: lehet valaki biztos abban, hogy egy adottság csak keveset számít, és bizonytalan abban, hogy mennyi a pontos arány.",
        "prep_2_h3": "Mit jelent egy határ?",
        "prep_2_p": "Az alsó és a felső határt úgy adja meg, hogy húsz hasonló becslésből tizenkilencszer közéjük essen az igazság. Ha a határok között csak ritkán van benne az igazság, a határok túl szűkek. A tapasztalat szerint a legtöbb szakértő először túl biztos, és túl szűk sávot ad; ezért érdemes a határokat kicsit szélesebbre venni, mint ami elsőre természetesnek tűnik.",
        "prep_3_h3": "Mit jelent az, hogy „90 %-ig biztos az irányban”?",
        "prep_3_p": "Nem azt, hogy a betegek 90 %-ánál így van. Azt jelenti: ha tíz ilyen kérdésben mondaná, hogy ez az irány igaz, kilencszer igaza lenne, egyszer tévedne. Az 50 % azt jelenti, hogy nem tudja, melyik irány igaz; a 99 % azt, hogy nagyon meglepődne, ha az ellenkezője derülne ki.",
        "prep_example_h3": "Kidolgozott példa",
        "prep_example_p": "Adottság: a felső gerinc magassága. A kolléga szerint az alacsony gerinc a rosszabb, és ebben 90 %-ig biztos. Száz magas gerincű betegből szerinte 85-nek lesz sikeres a fogsora; a valódi arány szerinte legalább 75, legfeljebb 92 lehet. Száz alacsony gerincűből 60-nak; legalább 45, legfeljebb 72. A legvalószínűbb számok tehát 85 és 60, a sávok pedig azt mutatják, mennyire biztos a két arányban.",
        "practice_h3": "Három gyakorlókérdés",
        "practice_intro": "Adjon mindhárom kérdésre egy legvalószínűbb értéket, és egy alsó és felső határt úgy, hogy húsz ilyen kérdésből tizenkilencszer közéjük essen a valódi érték. Ne keressen utána; éppen a bizonytalan tudásról szól a gyakorlat. Utána nézze meg, benne volt-e az igazság.",
        "practice_items": [
            ("1", "Hány kilométer Budapest és Bécs távolsága közúton?", "km", 243),
            ("2", "Hány éves volt Semmelweis Ignác, amikor meghalt?", "év", 47),
            ("3", "Magyarország lakosságából száz emberből hány 65 éves vagy idősebb?", "a százból", 21),
        ],
        "practice_dir_q": "Melyik folyó a hosszabb: a Duna vagy a Rajna? És mennyire biztos ebben?",
        "practice_dir_opts": [("duna", "a Duna"), ("rajna", "a Rajna")],
        "practice_dir_answer": "A Duna a hosszabb: körülbelül 2850 km, a Rajna körülbelül 1230 km. Ha 90 %-ot jelölt, azt mondta: tíz ilyen kérdésből kilencszer igaza lenne. Ha 99 %-ot, akkor szinte biztos volt.",
        "practice_check": "Megnézem a válaszokat",
        "practice_hit": "Benne volt. A valódi érték: {value} {unit}.",
        "practice_miss": "Kívül esett. A valódi érték: {value} {unit}.",
        "practice_missing": "Ehhez a kérdéshez nem adott meg mindhárom számot.",
        "practice_summary": "Három kérdésből {n} esetben volt a valódi érték a határai között.",
        "practice_narrow": "Ez kevesebb, mint amennyit a „húsz becslésből tizenkilenc” szabály várna: a határai valószínűleg túl szűkek. A kérdőívben adjon valamivel szélesebb sávokat.",
        "practice_ok": "Ez összhangban van a „húsz becslésből tizenkilenc” szabállyal. A kérdőívben is így adja meg a határokat.",
        "prep_continue": "Tovább a kérdőívre",
        "prep_link": "Felkészítő",
        "nav_admin": "Válaszok (vizsgálatvezető)",
        "logout": "Kilépés",
        "lang_other": "English",
        "login_title": "Belépés · PREDICT szakértői kérdőív",
        "login_eyebrow": "PREDICT-vizsgálat",
        "login_h1": "Kérdőív tapasztalt fogorvosoknak",
        "login_lead": "A teljes fogsor sikerét befolyásoló anatómiai adottságokról. A belépéshez írja be a vizsgálatvezetőtől kapott kódot.",
        "login_code": "Belépési kód",
        "login_button": "Belépés",
        "login_wrong": "Hibás belépési kód.",
        "start_title": "Tájékoztató · PREDICT szakértői kérdőív",
        "start_eyebrow": "PREDICT-vizsgálat · kérdőív tapasztalt fogorvosoknak",
        "start_h1": "Mit tanított Önnek a tapasztalat a teljes fogsorról?",
        "start_lead": "Arra kérjük, ossza meg velünk, mely anatómiai adottságok segítik, és melyek nehezítik a teljes lemezes fogsor sikerét. A kitöltés körülbelül 35–45 perc.",
        "current_eyebrow": "Megkezdett kitöltés",
        "current_answered": "{n} / {total} adottság megválaszolva",
        "current_submitted": "beküldve",
        "current_draft": "a válaszok el vannak mentve, folytathatja",
        "current_view": "Válaszaim megtekintése",
        "current_continue": "Folytatom",
        "greeting": "Tisztelt Kolléga!",
        "intro_1": "A teljes lemezes fogsor sikerét befolyásoló anatómiai adottságokról elődeink és tanáraink a tapasztalatuk alapján tanították, mi kedvező és mi kedvezőtlen. A PREDICT-vizsgálatban ezt a tapasztalati tudást szeretnénk összegyűjteni több tapasztalt kollégától, és összevetni a mért betegadatokkal.",
        "intro_2_lead": "Nincs jó vagy rossz válasz.",
        "intro_2": "Nem a tankönyvre, hanem az Ön saját, betegekkel szerzett tapasztalatára vagyunk kíváncsiak, akkor is, ha az eltér a tanultaktól. Ha valamiben bizonytalan, jelölje azt, ne találgasson: a bizonytalanság is fontos információ.",
        "success_h3": "Mit nevezünk sikeres fogsornak?",
        "success_def": "Sikeres a fogsor, ha három hónappal az átadás után a beteg a régi fogsorához képest érezhetően javult: jobban rág a rágástesztben, és jobb a szájegészséggel kapcsolatos életminősége a két kérdőívben (OHIP, GOHAI). Ezt a három mérés együttes, klinikailag érzékelhető javulásaként állapítjuk meg; a fogsor rendszeres hordása és a beteg elégedettsége ebben tükröződik.",
        "comparable_1": "Minden kérdésnél két, egyébként hasonló beteget képzeljen el, akik",
        "comparable_lead": "csak ebben az egy adottságban különböznek",
        "comparable_2": ": hasonló korúak, hasonló általános állapotúak, ugyanolyan gondos munkával készül a fogsoruk.",
        "how_h3": "Hogyan válaszoljon?",
        "how_intro": "Tizenhat anatómiai adottságról kérdezünk, mindegyiknél ugyanazt a néhány dolgot:",
        "how_1_lead": "Melyik változat a rosszabb?", "how_1": "Két változatot írunk le (A és B). Jelölheti azt is, hogy nincs érdemi különbség, vagy hogy nem tudja megítélni.",
        "how_2_lead": "Mennyire biztos az irányban?", "how_2": "Nem a betegek arányát kérdezzük, hanem azt, mennyire biztos abban, hogy valóban ez az irány igaz, és nem a fordítottja. 50 %: nem tudja, melyik. 90 %: ha tíz ilyen kérdésben így válaszolna, kilencszer igaza lenne. 99 %: szinte biztos.",
        "how_3_lead": "Száz beteg.", "how_3": "Ha 100 beteget látna az egyik, és 100-at a másik változattal, hánynak lenne sikeres a fogsora itt és ott? Például: 100 magas gerincű betegből 85-nek, 100 alacsony gerincűből 60-nak. A különbség így 25 beteg a százból.",
        "how_4_lead": "Hol lehet az igazság?", "how_4": "Mindkét számhoz adjon egy alsó és egy felső határt is úgy, hogy húsz hasonló becslésből tizenkilencszer ezen belül legyen a valódi arány. Ha a nagyságot nem tudja megbecsülni, jelölje be a „nem tudom megbecsülni” négyzetet; ez is értékes válasz.",
        "autosave_note": "A válaszok maguktól mentődnek. Bármikor abbahagyhatja, és ugyanezen a számítógépen később folytathatja. Minden adottságnál leírjuk, hogyan nézzük a vizsgálatban, hogy ugyanarra gondoljunk.",
        "data_h3": "Adatkezelés",
        "data_p": "A nevét csak a vizsgálatvezető látja, hogy tudja, kit kérdezett meg. A válaszokat kóddal (SZ01, SZ02 …) azonosítjuk, és kizárólag a többi kolléga válaszával együtt, összesítve használjuk fel. Egyéni válasz névvel nem kerül nyilvánosságra.",
        "name_label": "Az Ön neve *",
        "affiliation_label": "Munkahelye (nem kötelező)",
        "consent": "Hozzájárulok, hogy válaszaimat név nélkül, a többi kolléga válaszával együtt, tudományos célra felhasználják.",
        "start_button": "Kezdjük",
        "start_button_new": "Új kitöltést kezdek (a megkezdett megmarad)",
        "invite_eyebrow": "Személyes meghívó",
        "invite_lead": "Ezt a kérdőívet Önnek készítettük elő. Kérjük, ellenőrizze a nevét, jelölje be a hozzájárulást, és kezdje el a kitöltést.",
        "invite_invalid": "Ez a meghívó-link érvénytelen vagy már nem él. Kérjük, jelezze a vizsgálatvezetőnek.",
        "consent_missing": "A kitöltés megkezdéséhez a hozzájárulást meg kell jelölni.",
        "name_missing": "A kitöltés megkezdéséhez kérjük, adja meg a nevét.",
        "form_title": "Kérdőív",
        "breadcrumb": "← Vissza a tájékoztatóhoz",
        "form_lead": "Minden adottságnál ugyanaz a néhány kérdés. A csillaggal jelölt kérdések kellenek a beküldéshez, a többi hasznos, de kihagyható. A válaszok maguktól mentődnek.",
        "errors_title": "Még hiányzik vagy hibás:",
        "progress": "{n} / {total} adottság megválaszolva",
        "save_default": "A válaszok maguktól mentődnek.",
        "save_saving": "Mentés…", "save_saved": "Minden válasz el van mentve.",
        "save_failed": "A mentés most nem sikerült; beküldéskor minden válasz újra átadásra kerül.",
        "badge_done": "kész", "badge_pending": "még nincs kész",
        "a_eyebrow": "Először", "a_h2": "Néhány szó Önről",
        "a_diploma": "Melyik évben szerzett fogorvosi diplomát?",
        "a_szakvizsga": "Milyen szakvizsgája van?", "a_szakvizsga_ph": "pl. fogpótlástan",
        "a_evek": "Hány éve készít teljes fogsort? *",
        "a_evi": "Mostanában évente körülbelül hány teljes fogsort készít?",
        "a_fogsorok": "Körülbelül hány teljes fogsort készített eddig összesen? *",
        "a_fogsorok_opts": [("<100", "kevesebb mint 100"), ("100-500", "100–500"), ("500-1000", "500–1000"), ("1000-3000", "1000–3000"), (">3000", "több mint 3000")],
        "a_oktat": "Tanított-e fogpótlástant?",
        "a_oktat_opts": [("igen", "igen, most is"), ("nem", "nem"), ("korabban", "korábban igen")],
        "a_tevekenyseg": "Hol dolgozik főként?",
        "a_tevekenyseg_opts": [("egyetemi", "egyetemi klinikán"), ("maganpraxis", "magánpraxisban"), ("mindketto", "mindkettőben"), ("egyeb", "máshol")],
        "b_eyebrow": "Általában", "b_h2": "Néhány általános kérdés",
        "b_note": "Sikeres a fogsor, ha három hónappal az átadás után a beteg a régi fogsorához képest érezhetően javult: jobban rág, és jobbak az életminőség-kérdőívei (OHIP, GOHAI).",
        "b1": "Tapasztalata szerint 100 átlagos, teljes fogsorra szoruló betegből hánynak lesz sikeres a fogsora? *",
        "b1_unit": "beteg a százból",
        "b2": "Mennyiben múlik a siker az állcsontok adottságain? *",
        "b2_help": "A többi a kivitelezésen, a beteg alkalmazkodásán és egyéb tényezőkön múlik. Hány százalékot adna az adottságoknak?",
        "b2_unit": "% (0: semennyiben, 100: csak azon)",
        "b3": "Melyik állcsont adottságai számítanak többet?",
        "b3_opts": [("felso", "a felsőé"), ("also", "az alsóé"), ("egyforman", "egyformán")],
        "b3_ratio": "Ha az egyik többet számít: nagyjából hányszor annyit?",
        "b4": "Van-e olyan adottság, amelynél Ön eleve nem hagyományos teljes fogsort javasolna, hanem implantátumon elhorgonyzott fedőlemezes fogpótlást?",
        "b5": "Mennyire számít, hogy a betegnek volt-e már korábban teljes fogsora?",
        "b5_opts": [("alig", "alig"), ("kozepesen", "közepesen"), ("erosen", "nagyon")],
        "b5_ph": "megjegyzés, ha van",
        "items_h2": "Az anatómiai adottságok",
        "items_instruction": "Mindig két változatot írunk le, A-t és B-t; ahol a közepes is lehet a legjobb, ott egy közepes forgatókönyvet is. Azt jelölje, amelyikkel Ön szerint rosszabb kilátásokkal indul a fogsor. A „száz beteg” számok és a hozzájuk tartozó határok az egyes változatokra vonatkoznak; a program beküldés előtt jelzi, ha a számok ellentmondanak a jelölt iránynak.",
        "item_how": "Így nézzük a vizsgálatban:",
        "q_direction": "Melyik változat a rosszabb a fogsor sikere szempontjából? *",
        "dir_A_small": "A változat a rosszabb", "dir_B_small": "B változat a rosszabb",
        "dir_opt_small": "Egyik sem", "dir_opt": "a közepes a legjobb, a két véglet rosszabb",
        "dir_none": "Nincs érdemi különbség", "dir_dk": "Nem tudom megítélni",
        "q_certainty": "Mennyire biztos abban, hogy valóban ez az irány igaz, és nem a fordítottja? *",
        "certainty_help": "50 %: nem tudja, melyik irány igaz · 90 %: ha tíz ilyen kérdésben így válaszolna, kilencszer igaza lenne · 99 %: szinte biztos",
        "q_hundred": "Száz beteg: a legvalószínűbb szám és a határok",
        "hundred_help": "Képzeljen el 100 beteget az egyik és 100 beteget a másik változattal, egyébként hasonló betegeket. Hánynak lesz sikeres a fogsora? Írja be a legvalószínűbb számot, és mellé az alsó és felső határt úgy, hogy húsz hasonló becslésből tizenkilencszer ezen belül legyen a valódi arány.",
        "variant_A": "A változat", "variant_M": "Közepes változat", "variant_B": "B változat", "hundred_unit": "sikeres a százból",
        "point_label": "legvalószínűbb", "magnitude_unknown": "A nagyságát nem tudom megbecsülni (csak az irányt jelölöm)",
        "consistency_hint_direction": "A számok szerint a(z) {worse} változat a rosszabb, de fent a másikat jelölte.",
        "consistency_hint_range": "A legvalószínűbb szám essen az alsó és a felső határ közé.",
        "consistency_hint_nodiff": "„Nincs érdemi különbség”, de a két szám {diff} beteggel tér el.",
        "consistency_hint_optimum": "„A közepes a legjobb”, de a közepes szám nem a legmagasabb.",
        "q_range": "Mekkora lehet a különbség a két csoport között?",
        "range_help": "Hány beteg a különbség a százból, legalább és legfeljebb? Olyan határokat adjon, amelyeken kívül már nagyon meglepődne.",
        "range_min": "legalább", "range_max": "legfeljebb", "range_unit": "beteg",
        "comment_label": "Megjegyzés (nem kötelező)",
        "d_eyebrow": "Végül", "d_h2": "Összegzés",
        "d1": "Melyik öt adottság számít a legtöbbet a fogsor sikerében?", "d1_help": "A legfontosabbal kezdje.",
        "d2": "Melyik két adottság együtt a legrosszabb? Miért?",
        "d2_help": "Olyan párosra gondolunk, ahol a kettő együtt rosszabb, mint külön-külön összeadva.",
        "d3": "Van-e olyan adottság, amely ki tud egyenlíteni egy másik, kedvezőtlen adottságot? Hogyan?",
        "d4": "Mit hagytunk ki? Van-e olyan adottság, amelyet nem kérdeztünk, de Ön fontosnak tart?",
        "d5": "Összességében mennyire bízik a mai válaszaiban? *",
        "d5_opts": [("1", "1 · nagyon bizonytalan vagyok"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5 · nagyon biztos vagyok")],
        "d6": "Bármi más, amit szívesen hozzátenne",
        "submit_note": "Beküldés után a válaszok már nem módosíthatók.",
        "submit_button": "Válaszok beküldése",
        "submit_incomplete": "A kérdőív még nem küldhető be: kérjük, nézze át a hiányzó vagy hibás válaszokat.",
        "done_title": "Köszönjük · PREDICT szakértői kérdőív",
        "done_eyebrow": "Beküldve", "done_h1": "Köszönjük a válaszait!",
        "done_lead": "A(z) {code} kódú kitöltés beérkezett{when}.",
        "done_p": "Válaszait a többi kolléga válaszával együtt, összesítve használjuk fel a PREDICT-vizsgálatban. Köszönjük az idejét és a tapasztalatát!",
        "done_view": "Válaszaim megtekintése", "done_home": "Vissza a kezdőoldalra",
        "err_evek": "Hány éve készít teljes fogsort", "err_fogsorok": "Eddig készített teljes fogsorok száma",
        "err_b1": "Sikeres fogsorok aránya 100 betegből", "err_b2": "Mennyiben múlik az adottságokon",
        "err_direction": "melyik változat a rosszabb", "err_certainty": "mennyire biztos",
        "err_range": "a különbség alsó határa nagyobb a felsőnél", "err_d5": "Mennyire bízik a válaszaiban",
        "err_range_order": "a(z) {pole} változatnál az alsó határ nagyobb a felsőnél",
        "err_range_contains": "a(z) {pole} változatnál a legvalószínűbb szám nincs az alsó és a felső határ között",
        "err_magnitude_required": "kérjük a „száz beteg” számokat, vagy jelölje, hogy a nagyságot nem tudja megbecsülni",
        "err_range_required": "kérjük az alsó és felső határt is minden változathoz, vagy jelölje, hogy a nagyságot nem tudja megbecsülni",
        "err_numbers_direction": "a számok szerint a(z) {worse} változat a rosszabb, de a másikat jelölte rosszabbnak",
        "err_nodiff_numbers": "„nincs érdemi különbség”, de a két szám {diff} beteggel tér el",
        "err_optimum_numbers": "„a közepes a legjobb”, de a közepes szám nem a legmagasabb",
        "err_visszajelzes": "Miből tudja meg, hogyan vált be a fogsor",
    },
    "en": {
        "brand_small": "expert questionnaire",
        "role_q": "In what capacity are you answering? *",
        "role_opts": [("fogorvos", "as a dentist"), ("fogtechnikus", "as a dental technician")],
        "footer_line": "Semmelweis University · Department of Prosthodontics · PREDICT study",
        "prep_title": "Preparation · PREDICT expert questionnaire",
        "prep_eyebrow": "Preparation · about 5 minutes",
        "prep_h1": "Before you start: how do we put numbers on things we are not sure about?",
        "prep_lead": "The questionnaire asks something unusual: numbers about things nobody knows exactly. This short preparation and three practice questions help make sure your numbers mean what you think. The practice answers are not evaluated; they only give you feedback.",
        "prep_1_h3": "There are two kinds of uncertainty, and we ask about them separately",
        "prep_1_p": "One is the difference between patients: of a hundred patients, not everyone will have a successful denture even if their features are the same. This is what the “how many out of a hundred” number expresses. The other is the uncertainty of your own knowledge: you cannot know exactly whether that number is 60 or 75. This is what the lower and upper limits express. The two are not the same: one can be sure that a feature matters little and unsure about the exact proportion.",
        "prep_2_h3": "What does a limit mean?",
        "prep_2_p": "Give the lower and upper limit so that in nineteen out of twenty similar estimates the truth falls between them. If the truth is only rarely between your limits, the limits are too narrow. Experience shows that most experts are too sure at first and give too narrow a band; it is worth making the limits a little wider than feels natural at first.",
        "prep_3_h3": "What does “90 % sure about the direction” mean?",
        "prep_3_p": "Not that it is so in 90 % of patients. It means: if you said in ten such questions that this is the direction, you would be right nine times and wrong once. 50 % means you cannot tell which direction is true; 99 % means you would be very surprised if the opposite turned out to be the case.",
        "prep_example_h3": "Worked example",
        "prep_example_p": "Feature: height of the upper ridge. A colleague thinks the low ridge is worse and is 90 % sure. Of a hundred patients with a high ridge, 85 will have a successful denture in her view; the true proportion could be at least 75 and at most 92. Of a hundred with a low ridge, 60; at least 45 and at most 72. The most likely numbers are thus 85 and 60, and the bands show how sure she is about each proportion.",
        "practice_h3": "Three practice questions",
        "practice_intro": "For each question give a most likely value and a lower and upper limit such that in nineteen out of twenty such questions the true value would fall between them. Do not look it up; the exercise is exactly about uncertain knowledge. Then check whether the truth was inside.",
        "practice_items": [
            ("1", "How many kilometres is the road distance from Budapest to Vienna?", "km", 243),
            ("2", "How old was Ignaz Semmelweis when he died?", "years", 47),
            ("3", "Of a hundred people in Hungary, how many are 65 or older?", "in a hundred", 21),
        ],
        "practice_dir_q": "Which river is longer, the Danube or the Rhine? And how sure are you?",
        "practice_dir_opts": [("duna", "the Danube"), ("rajna", "the Rhine")],
        "practice_dir_answer": "The Danube is longer: about 2,850 km, the Rhine about 1,230 km. If you marked 90 %, you said you would be right nine times out of ten such questions. If 99 %, you were almost certain.",
        "practice_check": "Show the answers",
        "practice_hit": "Inside. The true value: {value} {unit}.",
        "practice_miss": "Outside. The true value: {value} {unit}.",
        "practice_missing": "You did not give all three numbers for this question.",
        "practice_summary": "In {n} of the three questions the true value was between your limits.",
        "practice_narrow": "That is fewer than the “nineteen out of twenty” rule would expect: your limits are probably too narrow. Give somewhat wider bands in the questionnaire.",
        "practice_ok": "That is in line with the “nineteen out of twenty” rule. Give the limits in the questionnaire the same way.",
        "prep_continue": "Continue to the questionnaire",
        "prep_link": "Preparation",
        "nav_admin": "Responses (investigator)",
        "logout": "Log out",
        "lang_other": "Magyar",
        "login_title": "Sign in · PREDICT expert questionnaire",
        "login_eyebrow": "PREDICT study",
        "login_h1": "Questionnaire for experienced dentists",
        "login_lead": "On the anatomical features that influence the success of complete dentures. Please enter the access code you received from the investigator.",
        "login_code": "Access code",
        "login_button": "Sign in",
        "login_wrong": "Wrong access code.",
        "start_title": "Information · PREDICT expert questionnaire",
        "start_eyebrow": "PREDICT study · questionnaire for experienced dentists",
        "start_h1": "What has experience taught you about complete dentures?",
        "start_lead": "We ask you to share which anatomical features help, and which hinder, the success of a complete denture. Completing it takes about 35–45 minutes.",
        "current_eyebrow": "Questionnaire in progress",
        "current_answered": "{n} / {total} features answered",
        "current_submitted": "submitted",
        "current_draft": "your answers are saved, you can continue",
        "current_view": "View my answers",
        "current_continue": "Continue",
        "greeting": "Dear Colleague,",
        "intro_1": "Our predecessors and teachers taught from experience which anatomical features are favourable and which are unfavourable for the success of a complete denture. In the PREDICT study we want to collect this experiential knowledge from several experienced colleagues and compare it with measured patient data.",
        "intro_2_lead": "There are no right or wrong answers.",
        "intro_2": "We are not asking about the textbook but about your own experience with patients, even where it differs from what you were taught. If you are unsure about something, mark that rather than guessing: uncertainty is valuable information too.",
        "success_h3": "What do we call a successful denture?",
        "success_def": "A denture is successful if, three months after delivery, the patient has clearly improved compared with the old denture: chews better in the chewing test, and reports better oral-health-related quality of life on the two questionnaires (OHIP, GOHAI). We determine this as the joint, clinically noticeable improvement of the three measures; regular wear and the patient's satisfaction are reflected in it.",
        "comparable_1": "For every question, imagine two otherwise similar patients who",
        "comparable_lead": "differ only in this one feature",
        "comparable_2": ": similar age, similar general health, dentures made with the same care.",
        "how_h3": "How to answer",
        "how_intro": "We ask about sixteen anatomical features, and the same few things for each:",
        "how_1_lead": "Which variant is worse?", "how_1": "We describe two variants (A and B). You can also mark that there is no real difference, or that you cannot judge.",
        "how_2_lead": "How sure are you about the direction?", "how_2": "We are not asking about the proportion of patients but how sure you are that this is really the direction, and not the opposite. 50 %: you cannot tell. 90 %: if you answered ten such questions this way, you would be right nine times. 99 %: almost certain.",
        "how_3_lead": "A hundred patients.", "how_3": "If you saw 100 patients with one variant and 100 with the other, how many would have a successful denture in each group? For example: 85 of 100 patients with a high ridge, 60 of 100 with a low ridge. The difference is then 25 patients in a hundred.",
        "how_4_lead": "Where could the truth lie?", "how_4": "For both numbers also give a lower and an upper limit such that in nineteen out of twenty similar estimates the true proportion would fall within them. If you cannot estimate the size, tick the “cannot estimate” box; that is a valuable answer too.",
        "autosave_note": "Your answers are saved automatically. You can stop at any time and continue later on the same computer. For each feature we describe how we record it in the study, so that we are thinking of the same thing.",
        "data_h3": "Data handling",
        "data_p": "Only the investigator sees your name, so that we know whom we asked. Answers are identified by a code (SZ01, SZ02 …) and used only pooled together with the answers of the other colleagues. No individual answer is published with a name.",
        "name_label": "Your name *",
        "affiliation_label": "Institution (optional)",
        "consent": "I agree that my answers may be used for scientific purposes, without my name, pooled with the answers of other colleagues.",
        "start_button": "Let's start",
        "start_button_new": "Start a new questionnaire (the one in progress is kept)",
        "invite_eyebrow": "Personal invitation",
        "invite_lead": "This questionnaire has been prepared for you. Please check your name, tick the consent box and start.",
        "invite_invalid": "This invitation link is invalid or no longer active. Please contact the investigator.",
        "consent_missing": "Please tick the consent box to start.",
        "name_missing": "Please enter your name to start.",
        "form_title": "Questionnaire",
        "breadcrumb": "← Back to the information page",
        "form_lead": "The same few questions for every feature. Questions marked with a star are needed to submit; the others are useful but optional. Your answers are saved automatically.",
        "errors_title": "Still missing or invalid:",
        "progress": "{n} / {total} features answered",
        "save_default": "Your answers are saved automatically.",
        "save_saving": "Saving…", "save_saved": "All answers are saved.",
        "save_failed": "Saving failed for now; all answers will be sent again when you submit.",
        "badge_done": "done", "badge_pending": "not yet complete",
        "a_eyebrow": "First", "a_h2": "A few words about you",
        "a_diploma": "In which year did you graduate in dentistry?",
        "a_szakvizsga": "What is your specialty qualification?", "a_szakvizsga_ph": "e.g. prosthodontics",
        "a_evek": "For how many years have you been making complete dentures? *",
        "a_evi": "About how many complete dentures do you make per year these days?",
        "a_fogsorok": "About how many complete dentures have you made in total? *",
        "a_fogsorok_opts": [("<100", "fewer than 100"), ("100-500", "100–500"), ("500-1000", "500–1000"), ("1000-3000", "1000–3000"), (">3000", "more than 3000")],
        "a_oktat": "Have you taught prosthodontics?",
        "a_oktat_opts": [("igen", "yes, currently"), ("nem", "no"), ("korabban", "in the past")],
        "a_tevekenyseg": "Where do you mainly work?",
        "a_tevekenyseg_opts": [("egyetemi", "university clinic"), ("maganpraxis", "private practice"), ("mindketto", "both"), ("egyeb", "elsewhere")],
        "b_eyebrow": "In general", "b_h2": "A few general questions",
        "b_note": "A denture is successful if, three months after delivery, the patient has clearly improved compared with the old denture: chews better, and scores better on the quality-of-life questionnaires (OHIP, GOHAI).",
        "b1": "In your experience, of 100 average patients needing a complete denture, how many will have a successful denture? *",
        "b1_unit": "patients in a hundred",
        "b2": "How much does success depend on the anatomy of the jaws? *",
        "b2_help": "The rest depends on the workmanship, the patient's adaptation and other factors. What percentage would you give to the anatomy?",
        "b2_unit": "% (0: not at all, 100: entirely)",
        "b3": "Which jaw's features matter more?",
        "b3_opts": [("felso", "the upper"), ("also", "the lower"), ("egyforman", "equally")],
        "b3_ratio": "If one matters more: roughly how many times as much?",
        "b4": "Is there any feature for which you would not recommend a conventional complete denture at all, but an implant-retained overdenture?",
        "b5": "How much does it matter whether the patient has had a complete denture before?",
        "b5_opts": [("alig", "hardly"), ("kozepesen", "moderately"), ("erosen", "a lot")],
        "b5_ph": "comment, if any",
        "items_h2": "The anatomical features",
        "items_instruction": "We always describe two variants, A and B; where the middle may be best, a middle scenario too. Mark the one with which, in your view, the denture starts with worse prospects. The “hundred patients” numbers and their limits refer to each variant; before submission the program flags numbers that contradict the marked direction.",
        "item_how": "How we record it in the study:",
        "q_direction": "Which variant is worse for the success of the denture? *",
        "dir_A_small": "Variant A is worse", "dir_B_small": "Variant B is worse",
        "dir_opt_small": "Neither", "dir_opt": "the middle is best, both extremes are worse",
        "dir_none": "No real difference", "dir_dk": "Cannot judge",
        "q_certainty": "How sure are you that this is really the direction, and not the opposite? *",
        "certainty_help": "50 %: you cannot tell which direction is true · 90 %: if you answered ten such questions this way, you would be right nine times · 99 %: almost certain",
        "q_hundred": "A hundred patients: the most likely number and the limits",
        "hundred_help": "Imagine 100 patients with one variant and 100 with the other, otherwise similar patients. How many will have a successful denture? Enter the most likely number, and next to it a lower and an upper limit such that in nineteen out of twenty similar estimates the true proportion would fall within them.",
        "variant_A": "Variant A", "variant_M": "Middle variant", "variant_B": "Variant B", "hundred_unit": "successful in a hundred",
        "point_label": "most likely", "magnitude_unknown": "I cannot estimate the size (I only mark the direction)",
        "consistency_hint_direction": "According to the numbers variant {worse} is worse, but you marked the other one above.",
        "consistency_hint_range": "The most likely number should lie between the lower and the upper limit.",
        "consistency_hint_nodiff": "“No meaningful difference”, but the two numbers differ by {diff} patients.",
        "consistency_hint_optimum": "“The middle is best”, but the middle number is not the highest.",
        "q_range": "How large could the difference between the two groups be?",
        "range_help": "How many patients in a hundred is the difference, at least and at most? Give limits outside which you would be very surprised.",
        "range_min": "at least", "range_max": "at most", "range_unit": "patients",
        "comment_label": "Comment (optional)",
        "d_eyebrow": "Finally", "d_h2": "Summary",
        "d1": "Which five features matter most for the success of the denture?", "d1_help": "Start with the most important.",
        "d2": "Which two features together are the worst? Why?",
        "d2_help": "We mean a pair where the two together are worse than the sum of the two separately.",
        "d3": "Is there a feature that can compensate for another, unfavourable feature? How?",
        "d4": "What did we leave out? Is there a feature we did not ask about but you consider important?",
        "d5": "Overall, how confident are you in your answers today? *",
        "d5_opts": [("1", "1 · very unsure"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5 · very confident")],
        "d6": "Anything else you would like to add",
        "submit_note": "After submission the answers can no longer be changed.",
        "submit_button": "Submit answers",
        "submit_incomplete": "The questionnaire cannot be submitted yet: please check the missing or invalid answers.",
        "done_title": "Thank you · PREDICT expert questionnaire",
        "done_eyebrow": "Submitted", "done_h1": "Thank you for your answers!",
        "done_lead": "Questionnaire {code} has been received{when}.",
        "done_p": "Your answers will be used pooled with those of the other colleagues in the PREDICT study. Thank you for your time and your experience!",
        "done_view": "View my answers", "done_home": "Back to the start page",
        "err_evek": "Years of making complete dentures", "err_fogsorok": "Number of complete dentures made",
        "err_b1": "Successful dentures out of 100 patients", "err_b2": "How much depends on the anatomy",
        "err_direction": "which variant is worse", "err_certainty": "how sure",
        "err_range": "the lower limit of the difference is above the upper limit", "err_d5": "Confidence in your answers",
        "err_range_order": "for variant {pole} the lower limit is above the upper limit",
        "err_range_contains": "for variant {pole} the most likely number is not between the lower and the upper limit",
        "err_magnitude_required": "please give the “hundred patients” numbers, or mark that you cannot estimate the size",
        "err_range_required": "please give the lower and upper limit for every variant, or mark that you cannot estimate the size",
        "err_numbers_direction": "according to the numbers variant {worse} is worse, but you marked the other one",
        "err_nodiff_numbers": "“no meaningful difference”, but the two numbers differ by {diff} patients",
        "err_optimum_numbers": "“the middle is best”, but the middle number is not the highest",
        "err_visszajelzes": "How you learn how the denture worked out",
    },
}


# Szerepfüggő szövegek: a fogtechnikusi változat felülírja az alap (fogorvosi)
# kulcsokat; a "_neutral" készlet akkor él, amikor a szerep még nem ismert
# (belépő oldal, kóddal indított kitöltés tájékoztatója).
ROLE_UI = {
    "_neutral": {
        "hu": {
            "login_h1": "Kérdőív tapasztalt fogorvosoknak és fogtechnikusoknak",
            "start_eyebrow": "PREDICT-vizsgálat · kérdőív tapasztalt fogorvosoknak és fogtechnikusoknak",
        },
        "en": {
            "login_h1": "Questionnaire for experienced dentists and dental technicians",
            "start_eyebrow": "PREDICT study · questionnaire for experienced dentists and dental technicians",
        },
    },
    "fogtechnikus": {
        "hu": {
            "start_eyebrow": "PREDICT-vizsgálat · kérdőív tapasztalt fogtechnikusoknak",
            "start_lead": "Arra kérjük, ossza meg velünk, mely anatómiai adottságok segítik, és melyek nehezítik a teljes lemezes fogsor sikerét, ahogy azt Ön a laborból, a mintákról és a visszakerülő munkákból látja. A kitöltés körülbelül 35–45 perc.",
            "intro_2": "Nem a tankönyvre, hanem az Ön saját, a munkája során szerzett tapasztalatára vagyunk kíváncsiak, akkor is, ha az eltér a tanultaktól. Ha valamit a mintáról, a laborból nem lehet megítélni, jelölje azt, ne találgasson: az is fontos információ.",
            "success_def": "Sikeres a fogsor, ha három hónappal az átadás után a beteg a régi fogsorához képest érezhetően javult: jobban rág a rágástesztben, és jobb a szájegészséggel kapcsolatos életminősége a két kérdőívben (OHIP, GOHAI). Ezt a három mérés együttes, klinikailag érzékelhető javulásaként állapítjuk meg; a fogsor rendszeres hordása és a beteg elégedettsége ebben tükröződik. Ezt a betegen mérjük; a laborból nem mindig látszik, ezért arra kérjük a becslést, amit a fogorvosi visszajelzésekből és a visszakerülő munkákból tapasztal.",
            "how_3": "Ha 100 ilyen beteg fogsorát készítené az egyik, és 100-ét a másik változattal, hánynak lenne sikeres a fogsora itt és ott? Például: 100 magas gerincű betegből 85-nek, 100 alacsony gerincűből 60-nak. A különbség így 25 beteg a százból.",
            "a_kepesites": "Melyik évben szerezte a fogtechnikusi képesítését?",
            "a_mester": "Van-e mesterfogtechnikusi vizsgája?",
            "a_mester_opts": [("igen", "igen"), ("nem", "nem")],
            "a_oktat": "Tanított-e fogtechnikus-tanulókat vagy hallgatókat?",
            "a_visszajelzes": "Miből tudja meg, hogyan vált be egy-egy fogsor? *",
            "a_visszajelzes_opts": [("rendszeres_fogorvosi", "a fogorvos rendszeresen visszajelez"), ("visszakerulo_munkak", "főleg a visszakerülő, javítandó munkákból"), ("kozvetlen_beteg", "közvetlen kapcsolatban vagyok a betegekkel"), ("egyeb", "máshonnan")],
            "a_tevekenyseg_opts": [("egyetemi", "egyetemi, klinikai laborban"), ("maganpraxis", "magánlaborban"), ("mindketto", "mindkettőben"), ("egyeb", "máshol")],
            "b_note": "Sikeres a fogsor, ha három hónappal az átadás után a beteg a régi fogsorához képest érezhetően javult: jobban rág, és jobbak az életminőség-kérdőívei (OHIP, GOHAI). Ezt a betegen mérjük, nem a laborba visszakerülésből.",
            "b1": "Tapasztalata szerint 100 átlagos teljes fogsorból hány lesz sikeres? *",
            "b2_help": "A többi a fogorvosi és a fogtechnikai kivitelezésen, a beteg alkalmazkodásán és egyéb tényezőkön múlik. Hány százalékot adna az adottságoknak?",
            "b4": "Van-e olyan adottság, amelynél Ön eleve nem hagyományos teljes fogsort, hanem implantátumon elhorgonyzott fedőlemezes fogpótlást javasolna a fogorvosnak?",
            "items_instruction": "Mindig két változatot írunk le, A-t és B-t; ahol a közepes is lehet a legjobb, ott egy közepes forgatókönyvet is. Azt jelölje, amelyikkel Ön szerint rosszabb kilátásokkal indul a fogsor. Ha egy adottságot a mintáról, a laborból nem lehet megítélni, jelölje a „nem tudom megítélni” választ. A „száz beteg” számok és a határaik az egyes változatokra vonatkoznak; a program beküldés előtt jelzi, ha a számok ellentmondanak a jelölt iránynak.",
            "hundred_help": "Képzeljen el 100 beteget az egyik és 100 beteget a másik változattal, egyébként hasonló betegeket, ugyanolyan gondos munkával. Hánynak lesz sikeres a fogsora? Írja be a legvalószínűbb számot, és mellé az alsó és felső határt úgy, hogy húsz hasonló becslésből tizenkilencszer ezen belül legyen a valódi arány.",
            "dir_dk": "Nem tudom megítélni (a laborból nem látszik)",
        },
        "en": {
            "start_eyebrow": "PREDICT study · questionnaire for experienced dental technicians",
            "start_lead": "We ask you to share which anatomical features help, and which hinder, the success of a complete denture, as you see it in the laboratory, on the casts and in the work that comes back. Completing it takes about 35–45 minutes.",
            "intro_2": "We are not asking about the textbook but about your own experience from your work, even where it differs from what you were taught. If something cannot be judged from the cast, in the laboratory, mark that rather than guessing: that is valuable information too.",
            "success_def": "A denture is successful if, three months after delivery, the patient has clearly improved compared with the old denture: chews better in the chewing test, and reports better oral-health-related quality of life on the two questionnaires (OHIP, GOHAI). We determine this as the joint, clinically noticeable improvement of the three measures; regular wear and the patient's satisfaction are reflected in it. This is measured on the patient; it is not always visible from the laboratory, so we ask for your estimate based on what you learn from the dentists' feedback and from the work that comes back.",
            "how_3": "If you made the dentures of 100 such patients with one variant and 100 with the other, how many would have a successful denture in each group? For example: 85 of 100 patients with a high ridge, 60 of 100 with a low ridge. The difference is then 25 patients in a hundred.",
            "a_kepesites": "In which year did you qualify as a dental technician?",
            "a_mester": "Do you hold a master dental technician qualification?",
            "a_mester_opts": [("igen", "yes"), ("nem", "no")],
            "a_oktat": "Have you taught dental technician trainees or students?",
            "a_visszajelzes": "How do you learn how a denture worked out? *",
            "a_visszajelzes_opts": [("rendszeres_fogorvosi", "the dentist gives regular feedback"), ("visszakerulo_munkak", "mainly from work that comes back for repair"), ("kozvetlen_beteg", "I am in direct contact with the patients"), ("egyeb", "from elsewhere")],
            "a_tevekenyseg_opts": [("egyetemi", "university or clinic laboratory"), ("maganpraxis", "private laboratory"), ("mindketto", "both"), ("egyeb", "elsewhere")],
            "b_note": "A denture is successful if, three months after delivery, the patient has clearly improved compared with the old denture: chews better, and scores better on the quality-of-life questionnaires (OHIP, GOHAI). This is measured on the patient, not by whether the work comes back to the laboratory.",
            "b1": "In your experience, of 100 average complete dentures, how many will be successful? *",
            "b2_help": "The rest depends on the dentist's and the technician's workmanship, the patient's adaptation and other factors. What percentage would you give to the anatomy?",
            "b4": "Is there a feature for which you would advise the dentist from the outset to make an implant-retained overdenture rather than a conventional complete denture?",
            "items_instruction": "We always describe two variants, A and B; where the middle may be best, a middle scenario too. Mark the one with which, in your view, the denture starts with worse prospects. If a feature cannot be judged from the cast, in the laboratory, choose “cannot judge”. The “hundred patients” numbers and their limits refer to each variant; before submission the program flags numbers that contradict the marked direction.",
            "hundred_help": "Imagine 100 patients with one variant and 100 with the other, otherwise similar patients, dentures made with the same care. How many will have a successful denture? Enter the most likely number, and next to it a lower and an upper limit such that in nineteen out of twenty similar estimates the true proportion would fall within them.",
            "dir_dk": "Cannot judge (not visible from the laboratory)",
        },
    },
}


def ui_texts(lang="hu", role="fogorvos"):
    """A felület szövegei a kért nyelven és szerepben; role=None → semleges
    (szerep nélküli) változat."""
    key = "en" if lang == "en" else "hu"
    texts = dict(UI[key])
    texts.update(ROLE_UI.get(role if role in ROLES else "_neutral", {}).get(key, {}))
    return texts
