"""Kétnyelvű szövegek a szakértői kérdőívhez (magyar és angol).

A magyar a kanonikus változat; az angol a külföldi kollégáknak. A tételek
kódjai és a válaszkódok nyelvfüggetlenek, csak a megjelenített szöveg változik.
"""

LANGS = ("hu", "en")

# A PREDICT mozaikszó feloldása; a meghívólevélben egyszer, az első említésnél
# jelenik meg (a vizsgálatvezető által megadott hivatalos cím).
STUDY_ACRONYM = {
    "hu": ("Prognostic evaluation of the edentulous: inspecting critical anatomy, azaz a fogatlan páciens prognosztikai "
           "értékelése a meghatározó anatómiai adottságok vizsgálatával"),
    "en": "Prognostic evaluation of the edentulous: inspecting critical anatomy",
}

JAW_LABELS = {
    "hu": {"Felső állcsont": "Felső állcsont", "Alsó állcsont": "Alsó állcsont"},
    "en": {"Felső állcsont": "Upper jaw", "Alsó állcsont": "Lower jaw"},
}

IRANY_LABELS = {
    "hu": {
        "A_kedvezotlenebb": "az A változat a rosszabb",
        "B_kedvezotlenebb": "a B változat a rosszabb",
        "nem_monoton": "a közepes a legjobb, a két véglet rosszabb",
        "nincs_kulonbseg": "nincs érdemi különbség",
        "nem_tudom": "nem tudom megítélni",
    },
    "en": {
        "A_kedvezotlenebb": "variant A is worse",
        "B_kedvezotlenebb": "variant B is worse",
        "nem_monoton": "the middle is best, both extremes are worse",
        "nincs_kulonbseg": "no real difference",
        "nem_tudom": "cannot judge",
    },
}

# Az angol tételszövegek kódonként; a magyar a regiszterben (expert_priors.ITEMS).
ITEM_TEXT_EN = {
    "F1": {
        "nev": "Height of the upper ridge",
        "rogzit": "On the plaster cast we measure how high the upper alveolar ridge is.",
        "A": "high, well-preserved ridge", "B": "low, resorbed ridge",
        "kuszob": "Below what height would you call the upper ridge low? (mm)",
    },
    "F2": {
        "nev": "Undercut areas of the upper jaw",
        "rogzit": "On the cast we measure how much undercut area the upper jaw has.",
        "A": "little or no undercut", "B": "large undercut",
        "kuszob": "If a moderate amount is best: roughly what amount of undercut is ideal? (a few words)",
    },
    "F3": {
        "nev": "Height of the palate",
        "rogzit": "On the cast we measure the height of the palatal vault.",
        "A": "high, vaulted palate", "B": "flat palate",
        "kuszob": "Below what height would you call the palate flat? (mm)",
    },
    "F4": {
        "nev": "Shape of the upper ridge arch",
        "rogzit": "On the cast we measure the arch angle: a larger angle means a squarer arch, a smaller one a tapered, V-shaped arch.",
        "A": "square, broad arch", "B": "tapered, V-shaped arch",
        "kuszob": "Is there an angle above which there is no further benefit? (°)",
    },
    "F5": {
        "nev": "Flabby ridge in the upper jaw",
        "rogzit": "At the examination we note: none; flabby tuberosities; flabby anterior ridge.",
        "A": "no flabby ridge", "B": "flabby ridge present",
        "subs": {"lokalizacio": {"kerdes": "If present: which is worse?",
                                 "opciok": {"frontalis": "on the anterior ridge", "tuberalis": "on the tuberosities", "egyforma": "the same", "nem_tudom": "don't know"}}},
    },
    "F6": {
        "nev": "Position of the upper and lower ridge crests relative to each other",
        "rogzit": "On the cast we measure whether the upper and lower ridge crests lie vertically above each other (90°) or deviate from each other.",
        "A": "the two crests lie above each other", "B": "the two crests deviate considerably",
        "kuszob": "How large a deviation would you already consider significant? (°)",
        "subs": {"irany_szamit": {"kerdes": "Does the direction of the deviation matter (lower arch wider, or upper arch wider)?",
                                  "opciok": {"igen": "yes", "nem": "no", "nem_tudom": "don't know"}}},
    },
    "F7": {
        "nev": "Torus palatinus",
        "rogzit": "At the examination we note: none; flat (plateau-shaped); spindle-shaped.",
        "A": "no torus", "B": "torus present (flat or spindle-shaped)",
        "subs": {"alak_rosszabb": {"kerdes": "If present: which shape is worse?",
                                   "opciok": {"orso": "the spindle-shaped", "plato": "the flat one", "egyforma": "the same", "nem_tudom": "don't know"}}},
    },
    "F8": {
        "nev": "What opposes the upper denture (antagonist)",
        "rogzit": "At the examination we note: none, being made now; removable denture (complete denture, overdenture, metal-framework partial); retained natural teeth or fixed restoration.",
        "A": "removable denture in the opposing jaw", "B": "retained natural teeth or fixed restoration",
        "subs": {"kategoria_vagy_interakcio": {"kerdes": "Do you think the type of antagonist itself matters, or rather the direction of the forces (for example a forced scissor bite on a resorbed upper jaw)?",
                                               "opciok": {"kategoria": "the type of antagonist", "interakcio": "the direction of the forces", "mindketto": "both", "nem_tudom": "don't know"}}},
    },
    "A1": {
        "nev": "Shape and height of the lower ridge (Kaán classification)",
        "rogzit": "At the examination we grade the lower ridge in five classes: (1) preserved throughout; (2) preserved anteriorly, flat laterally; (3) flat throughout; (4) negative; (5) deepened negative. On the cast we also measure the ridge height.",
        "A": "ridge preserved throughout (1)", "B": "deepened negative ridge (5)",
        "kuszob": "Below what height would you call the lower ridge resorbed? (mm)",
        "subs": {
            "legnagyobb_ugras": {"kerdes": "Between which two classes does the outlook worsen the most?",
                                 "opciok": {"1_2": "between 1 and 2", "2_3": "between 2 and 3", "3_4": "between 3 and 4", "4_5": "between 4 and 5", "egyenletes": "roughly evenly"}},
            "negy_ot_kulonbseg": {"kerdes": "Is there a real difference between a negative and a deepened negative ridge?",
                                  "opciok": {"igen": "yes", "nem": "no", "nem_tudom": "don't know"}},
        },
    },
    "A3": {
        "nev": "The buccinator pouch",
        "rogzit": "At the examination we note what the pouch does on mouth opening: it narrows; it widens; or its surface is lobulated.",
        "A": "pouch that narrows on opening", "B": "pouch that widens on opening",
        "subs": {"lebenyezett": {"kerdes": "And the lobulated pouch?",
                                 "opciok": {"legkedvezobb": "that is the best", "koztes": "in between", "legkedvezotlenebb": "that is the worst", "nem_tudom": "don't know"}}},
    },
    "A4": {
        "nev": "Torus mandibularis",
        "rogzit": "At the examination we note on both sides: none; small; large.",
        "A": "no torus", "B": "torus present (small or large)",
        "subs": {"nagy_vs_kicsi": {"kerdes": "If present: how much worse is a large torus than a small one?",
                                   "opciok": {"alig": "hardly", "kozepesen": "moderately", "sokkal": "much", "nem_tudom": "don't know"}}},
    },
    "A5": {
        "nev": "The lingual pouch during swallowing",
        "rogzit": "At the examination we place a finger in the pouch and the patient swallows: the muscles press the finger against the jaw; they do not narrow the pouch; or they push the finger outwards.",
        "A": "the muscles press the finger against the jaw", "B": "the muscles push the finger outwards",
        "subs": {"nem_szukit_helye": {"kerdes": "And if the muscles do not narrow the pouch?",
                                      "opciok": {"A_kozel": "that is closer to A", "kozepen": "in between", "B_kozel": "that is closer to B", "nem_tudom": "don't know"}}},
    },
    "TUB": {
        "nev": "The retromolar pad (tuberculum alveolare mandibulae)",
        "rogzit": "We look at four things: whether attached gingiva covers it; its shape (pear-shaped, small, fold-like); its inclination to the ridge; whether it moves on mouth opening.",
        "A": "covered by attached gingiva, well shaped, immobile", "B": "uncovered, fold-like, mobile",
        "subs": {"legfontosabb": {"kerdes": "Which of the four matters most?",
                                  "opciok": {"A6": "the attached gingiva cover", "A7": "its shape", "A8": "its inclination", "A9": "whether it moves", "nem_tudom": "don't know"}}},
    },
    "A10": {
        "nev": "Sagittal relation of the jaws",
        "rogzit": "On the cast we measure whether the lower jaw sits further forward or further back relative to the upper jaw; essentially the Angle class.",
        "A": "Angle Class I, normal relation", "B": "Angle Class II or III, deviating relation",
        "subs": {"melyik_rosszabb": {"kerdes": "If a deviation is bad: which is worse?",
                                     "opciok": {"angle_II": "Angle Class II", "angle_III": "Angle Class III", "egyforma": "the same", "nem_tudom": "don't know"}}},
    },
    "A11": {
        "nev": "The floor of the mouth",
        "rogzit": "At the examination we note: not bulging; softly bulging; firm and bulging.",
        "A": "softly bulging floor of the mouth", "B": "firm, bulging floor of the mouth",
        "subs": {"nem_elodomborodo_helye": {"kerdes": "And the non-bulging floor of the mouth?",
                                            "opciok": {"A_kozel": "that is closer to A", "kozepen": "in between", "B_kozel": "that is closer to B", "nem_tudom": "don't know"}}},
    },
    "A12": {
        "nev": "Genial tubercles (spinae mentales)",
        "rogzit": "At the examination we note: not palpable; palpable; tender to pressure.",
        "A": "not palpable", "B": "palpable or tender to pressure",
        "subs": {"erzekeny_vs_tapinthato": {"kerdes": "If palpable: how much worse is it when it is also tender to pressure?",
                                            "opciok": {"alig": "hardly", "kozepesen": "moderately", "sokkal": "much", "nem_tudom": "don't know"}}},
    },
}

UI = {
    "hu": {
        "brand_small": "szakértői kérdőív",
        "nav_admin": "Válaszok (vizsgálatvezető)",
        "logout": "Kilépés",
        "lang_other": "English",
        "login_title": "Belépés · PREDICT szakértői kérdőív",
        "login_eyebrow": "PREDICT-vizsgálat",
        "login_h1": "Kérdőív tapasztalt fogorvosoknak",
        "login_lead": "A teljes fogsor sikerét befolyásoló anatómiai adottságokról. A belépéshez írja be a vizsgálatvezetőtől kapott kódot.",
        "login_code": "Belépési kód",
        "login_button": "Belépés",
        "login_wrong": "Hibás belépési kód.",
        "start_title": "Tájékoztató · PREDICT szakértői kérdőív",
        "start_eyebrow": "PREDICT-vizsgálat · kérdőív tapasztalt fogorvosoknak",
        "start_h1": "Mit tanított Önnek a tapasztalat a teljes fogsorról?",
        "start_lead": "Arra kérjük, ossza meg velünk, mely anatómiai adottságok segítik, és melyek nehezítik a teljes lemezes fogsor sikerét. A kitöltés körülbelül 25–35 perc.",
        "current_eyebrow": "Megkezdett kitöltés",
        "current_answered": "{n} / {total} adottság megválaszolva",
        "current_submitted": "beküldve",
        "current_draft": "a válaszok el vannak mentve, folytathatja",
        "current_view": "Válaszaim megtekintése",
        "current_continue": "Folytatom",
        "greeting": "Tisztelt Kolléga!",
        "intro_1": "A teljes lemezes fogsor sikerét befolyásoló anatómiai adottságokról elődeink és tanáraink a tapasztalatuk alapján tanították, mi kedvező és mi kedvezőtlen. A PREDICT-vizsgálatban ezt a tapasztalati tudást szeretnénk összegyűjteni több tapasztalt kollégától, és összevetni a mért betegadatokkal.",
        "intro_2_lead": "Nincs jó vagy rossz válasz.",
        "intro_2": "Nem a tankönyvre, hanem az Ön saját, betegekkel szerzett tapasztalatára vagyunk kíváncsiak, akkor is, ha az eltér a tanultaktól. Ha valamiben bizonytalan, jelölje azt, ne találgasson: a bizonytalanság is fontos információ.",
        "success_h3": "Mit nevezünk sikeres fogsornak?",
        "success_def": "Sikeres a fogsor, ha a beteg az átadás utáni fél évben rendszeresen hordja, tud vele enni, nincs komoly fájdalma vagy nyomási panasza, és elégedett vele.",
        "comparable_1": "Minden kérdésnél két, egyébként hasonló beteget képzeljen el, akik",
        "comparable_lead": "csak ebben az egy adottságban különböznek",
        "comparable_2": ": hasonló korúak, hasonló általános állapotúak, ugyanolyan gondos munkával készül a fogsoruk.",
        "how_h3": "Hogyan válaszoljon?",
        "how_intro": "Tizenhat anatómiai adottságról kérdezünk, mindegyiknél ugyanazt a néhány dolgot:",
        "how_1_lead": "Melyik változat a rosszabb?", "how_1": "Két változatot írunk le (A és B). Jelölheti azt is, hogy nincs érdemi különbség, vagy hogy nem tudja megítélni.",
        "how_2_lead": "Mennyire biztos ebben?", "how_2": "50 %: mintha pénzt dobna fel. 90 %: tízből kilencszer így van. 99 %: szinte biztos.",
        "how_3_lead": "Száz beteg.", "how_3": "Ha 100 beteget látna az egyik, és 100-at a másik változattal, hánynak lenne sikeres a fogsora itt és ott? Például: 100 magas gerincű betegből 85-nek, 100 alacsony gerincűből 60-nak. A különbség így 25 beteg a százból.",
        "how_4_lead": "Legalább és legfeljebb.", "how_4": "Mekkora lehet ez a különbség a legkevesebb és a legtöbb esetben? Olyan határokat adjon, amelyeken kívül már nagyon meglepődne.",
        "autosave_note": "A válaszok maguktól mentődnek. Bármikor abbahagyhatja, és ugyanezen a számítógépen később folytathatja. Minden adottságnál leírjuk, hogyan nézzük a vizsgálatban, hogy ugyanarra gondoljunk.",
        "data_h3": "Adatkezelés",
        "data_p": "A nevét csak a vizsgálatvezető látja, hogy tudja, kit kérdezett meg. A válaszokat kóddal (SZ01, SZ02 …) azonosítjuk, és kizárólag a többi kolléga válaszával együtt, összesítve használjuk fel. Egyéni válasz névvel nem kerül nyilvánosságra.",
        "name_label": "Az Ön neve *",
        "affiliation_label": "Munkahelye (nem kötelező)",
        "consent": "Hozzájárulok, hogy válaszaimat név nélkül, a többi kolléga válaszával együtt, tudományos célra felhasználják.",
        "start_button": "Kezdjük",
        "start_button_new": "Új kitöltést kezdek (a megkezdett megmarad)",
        "invite_eyebrow": "Személyes meghívó",
        "invite_lead": "Ezt a kérdőívet Önnek készítettük elő. Kérjük, ellenőrizze a nevét, jelölje be a hozzájárulást, és kezdje el a kitöltést.",
        "invite_invalid": "Ez a meghívó-link érvénytelen vagy már nem él. Kérjük, jelezze a vizsgálatvezetőnek.",
        "consent_missing": "A kitöltés megkezdéséhez a hozzájárulást meg kell jelölni.",
        "name_missing": "A kitöltés megkezdéséhez kérjük, adja meg a nevét.",
        "form_title": "Kérdőív",
        "breadcrumb": "← Vissza a tájékoztatóhoz",
        "form_lead": "Minden adottságnál ugyanaz a néhány kérdés. A csillaggal jelölt kérdések kellenek a beküldéshez, a többi hasznos, de kihagyható. A válaszok maguktól mentődnek.",
        "errors_title": "Még hiányzik vagy hibás:",
        "progress": "{n} / {total} adottság megválaszolva",
        "save_default": "A válaszok maguktól mentődnek.",
        "save_saving": "Mentés…", "save_saved": "Minden válasz el van mentve.",
        "save_failed": "A mentés most nem sikerült; beküldéskor minden válasz újra átadásra kerül.",
        "badge_done": "kész", "badge_pending": "még nincs kész",
        "a_eyebrow": "Először", "a_h2": "Néhány szó Önről",
        "a_diploma": "Melyik évben szerzett fogorvosi diplomát?",
        "a_szakvizsga": "Milyen szakvizsgája van?", "a_szakvizsga_ph": "pl. fogpótlástan",
        "a_evek": "Hány éve készít teljes fogsort? *",
        "a_evi": "Mostanában évente körülbelül hány teljes fogsort készít?",
        "a_fogsorok": "Körülbelül hány teljes fogsort készített eddig összesen? *",
        "a_fogsorok_opts": [("<100", "kevesebb mint 100"), ("100-500", "100–500"), ("500-1000", "500–1000"), ("1000-3000", "1000–3000"), (">3000", "több mint 3000")],
        "a_oktat": "Tanított-e fogpótlástant?",
        "a_oktat_opts": [("igen", "igen, most is"), ("nem", "nem"), ("korabban", "korábban igen")],
        "a_tevekenyseg": "Hol dolgozik főként?",
        "a_tevekenyseg_opts": [("egyetemi", "egyetemi klinikán"), ("maganpraxis", "magánpraxisban"), ("mindketto", "mindkettőben"), ("egyeb", "máshol")],
        "b_eyebrow": "Általában", "b_h2": "Néhány általános kérdés",
        "b_note": "Sikeres a fogsor, ha a beteg fél év múlva is hordja, tud vele enni, nincs komoly panasza, és elégedett vele.",
        "b1": "Tapasztalata szerint 100 átlagos, teljes fogsorra szoruló betegből hánynak lesz sikeres a fogsora? *",
        "b1_unit": "beteg a százból",
        "b2": "Mennyiben múlik a siker az állcsontok adottságain? *",
        "b2_help": "A többi a kivitelezésen, a beteg alkalmazkodásán és egyéb tényezőkön múlik. Hány százalékot adna az adottságoknak?",
        "b2_unit": "% (0: semennyiben, 100: csak azon)",
        "b3": "Melyik állcsont adottságai számítanak többet?",
        "b3_opts": [("felso", "a felsőé"), ("also", "az alsóé"), ("egyforman", "egyformán")],
        "b3_ratio": "Ha az egyik többet számít: nagyjából hányszor annyit?",
        "b4": "Van-e olyan adottság, amelynél Ön eleve nem hagyományos teljes fogsort javasolna, hanem implantátumon elhorgonyzott fedőlemezes fogpótlást?",
        "b5": "Mennyire számít, hogy a betegnek volt-e már korábban teljes fogsora?",
        "b5_opts": [("alig", "alig"), ("kozepesen", "közepesen"), ("erosen", "nagyon")],
        "b5_ph": "megjegyzés, ha van",
        "items_h2": "Az anatómiai adottságok",
        "items_instruction": "Mindig két változatot írunk le, A-t és B-t. Azt jelölje, amelyikkel Ön szerint rosszabb kilátásokkal indul a fogsor. A „száz beteg” és a „mennyire biztos” kérdés mindig arra a változatra vonatkozik, amelyiket rosszabbnak jelölte.",
        "item_how": "Így nézzük a vizsgálatban:",
        "q_direction": "Melyik változat a rosszabb a fogsor sikere szempontjából? *",
        "dir_A_small": "A változat a rosszabb", "dir_B_small": "B változat a rosszabb",
        "dir_opt_small": "Egyik sem", "dir_opt": "a közepes a legjobb, a két véglet rosszabb",
        "dir_none": "Nincs érdemi különbség", "dir_dk": "Nem tudom megítélni",
        "q_certainty": "Mennyire biztos ebben? *",
        "certainty_help": "50 %: mintha pénzt dobna fel · 90 %: tízből kilencszer így van · 99 %: szinte biztos",
        "q_hundred": "Száz beteg",
        "hundred_help": "Képzeljen el 100 beteget az A és 100 beteget a B változattal, egyébként hasonló betegeket. Hánynak lesz sikeres a fogsora?",
        "variant_A": "A változat", "variant_B": "B változat", "hundred_unit": "sikeres a százból",
        "q_range": "Mekkora lehet a különbség a két csoport között?",
        "range_help": "Hány beteg a különbség a százból, legalább és legfeljebb? Olyan határokat adjon, amelyeken kívül már nagyon meglepődne.",
        "range_min": "legalább", "range_max": "legfeljebb", "range_unit": "beteg",
        "comment_label": "Megjegyzés (nem kötelező)",
        "d_eyebrow": "Végül", "d_h2": "Összegzés",
        "d1": "Melyik öt adottság számít a legtöbbet a fogsor sikerében?", "d1_help": "A legfontosabbal kezdje.",
        "d2": "Melyik két adottság együtt a legrosszabb? Miért?",
        "d2_help": "Olyan párosra gondolunk, ahol a kettő együtt rosszabb, mint külön-külön összeadva.",
        "d3": "Van-e olyan adottság, amely ki tud egyenlíteni egy másik, kedvezőtlen adottságot? Hogyan?",
        "d4": "Mit hagytunk ki? Van-e olyan adottság, amelyet nem kérdeztünk, de Ön fontosnak tart?",
        "d5": "Összességében mennyire bízik a mai válaszaiban? *",
        "d5_opts": [("1", "1 · nagyon bizonytalan vagyok"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5 · nagyon biztos vagyok")],
        "d6": "Bármi más, amit szívesen hozzátenne",
        "submit_note": "Beküldés után a válaszok már nem módosíthatók.",
        "submit_button": "Válaszok beküldése",
        "submit_incomplete": "A kérdőív még nem küldhető be: kérjük, nézze át a hiányzó vagy hibás válaszokat.",
        "done_title": "Köszönjük · PREDICT szakértői kérdőív",
        "done_eyebrow": "Beküldve", "done_h1": "Köszönjük a válaszait!",
        "done_lead": "A(z) {code} kódú kitöltés beérkezett{when}.",
        "done_p": "Válaszait a többi kolléga válaszával együtt, összesítve használjuk fel a PREDICT-vizsgálatban. Köszönjük az idejét és a tapasztalatát!",
        "done_view": "Válaszaim megtekintése", "done_home": "Vissza a kezdőoldalra",
        "err_evek": "Hány éve készít teljes fogsort", "err_fogsorok": "Eddig készített teljes fogsorok száma",
        "err_b1": "Sikeres fogsorok aránya 100 betegből", "err_b2": "Mennyiben múlik az adottságokon",
        "err_direction": "melyik változat a rosszabb", "err_certainty": "mennyire biztos",
        "err_range": "a különbség alsó határa nagyobb a felsőnél", "err_d5": "Mennyire bízik a válaszaiban",
    },
    "en": {
        "brand_small": "expert questionnaire",
        "nav_admin": "Responses (investigator)",
        "logout": "Log out",
        "lang_other": "Magyar",
        "login_title": "Sign in · PREDICT expert questionnaire",
        "login_eyebrow": "PREDICT study",
        "login_h1": "Questionnaire for experienced dentists",
        "login_lead": "On the anatomical features that influence the success of complete dentures. Please enter the access code you received from the investigator.",
        "login_code": "Access code",
        "login_button": "Sign in",
        "login_wrong": "Wrong access code.",
        "start_title": "Information · PREDICT expert questionnaire",
        "start_eyebrow": "PREDICT study · questionnaire for experienced dentists",
        "start_h1": "What has experience taught you about complete dentures?",
        "start_lead": "We ask you to share which anatomical features help, and which hinder, the success of a complete denture. Completing it takes about 25–35 minutes.",
        "current_eyebrow": "Questionnaire in progress",
        "current_answered": "{n} / {total} features answered",
        "current_submitted": "submitted",
        "current_draft": "your answers are saved, you can continue",
        "current_view": "View my answers",
        "current_continue": "Continue",
        "greeting": "Dear Colleague,",
        "intro_1": "Our predecessors and teachers taught from experience which anatomical features are favourable and which are unfavourable for the success of a complete denture. In the PREDICT study we want to collect this experiential knowledge from several experienced colleagues and compare it with measured patient data.",
        "intro_2_lead": "There are no right or wrong answers.",
        "intro_2": "We are not asking about the textbook but about your own experience with patients, even where it differs from what you were taught. If you are unsure about something, mark that rather than guessing: uncertainty is valuable information too.",
        "success_h3": "What do we call a successful denture?",
        "success_def": "A denture is successful if, in the six months after delivery, the patient wears it regularly, can eat with it, has no serious pain or pressure complaints, and is satisfied with it.",
        "comparable_1": "For every question, imagine two otherwise similar patients who",
        "comparable_lead": "differ only in this one feature",
        "comparable_2": ": similar age, similar general health, dentures made with the same care.",
        "how_h3": "How to answer",
        "how_intro": "We ask about sixteen anatomical features, and the same few things for each:",
        "how_1_lead": "Which variant is worse?", "how_1": "We describe two variants (A and B). You can also mark that there is no real difference, or that you cannot judge.",
        "how_2_lead": "How sure are you?", "how_2": "50 %: like tossing a coin. 90 %: nine times out of ten. 99 %: almost certain.",
        "how_3_lead": "A hundred patients.", "how_3": "If you saw 100 patients with one variant and 100 with the other, how many would have a successful denture in each group? For example: 85 of 100 patients with a high ridge, 60 of 100 with a low ridge. The difference is then 25 patients in a hundred.",
        "how_4_lead": "At least and at most.", "how_4": "How large could this difference be at the least and at the most? Give limits outside which you would be very surprised.",
        "autosave_note": "Your answers are saved automatically. You can stop at any time and continue later on the same computer. For each feature we describe how we record it in the study, so that we are thinking of the same thing.",
        "data_h3": "Data handling",
        "data_p": "Only the investigator sees your name, so that we know whom we asked. Answers are identified by a code (SZ01, SZ02 …) and used only pooled together with the answers of the other colleagues. No individual answer is published with a name.",
        "name_label": "Your name *",
        "affiliation_label": "Institution (optional)",
        "consent": "I agree that my answers may be used for scientific purposes, without my name, pooled with the answers of other colleagues.",
        "start_button": "Let's start",
        "start_button_new": "Start a new questionnaire (the one in progress is kept)",
        "invite_eyebrow": "Personal invitation",
        "invite_lead": "This questionnaire has been prepared for you. Please check your name, tick the consent box and start.",
        "invite_invalid": "This invitation link is invalid or no longer active. Please contact the investigator.",
        "consent_missing": "Please tick the consent box to start.",
        "name_missing": "Please enter your name to start.",
        "form_title": "Questionnaire",
        "breadcrumb": "← Back to the information page",
        "form_lead": "The same few questions for every feature. Questions marked with a star are needed to submit; the others are useful but optional. Your answers are saved automatically.",
        "errors_title": "Still missing or invalid:",
        "progress": "{n} / {total} features answered",
        "save_default": "Your answers are saved automatically.",
        "save_saving": "Saving…", "save_saved": "All answers are saved.",
        "save_failed": "Saving failed for now; all answers will be sent again when you submit.",
        "badge_done": "done", "badge_pending": "not yet complete",
        "a_eyebrow": "First", "a_h2": "A few words about you",
        "a_diploma": "In which year did you graduate in dentistry?",
        "a_szakvizsga": "What is your specialty qualification?", "a_szakvizsga_ph": "e.g. prosthodontics",
        "a_evek": "For how many years have you been making complete dentures? *",
        "a_evi": "About how many complete dentures do you make per year these days?",
        "a_fogsorok": "About how many complete dentures have you made in total? *",
        "a_fogsorok_opts": [("<100", "fewer than 100"), ("100-500", "100–500"), ("500-1000", "500–1000"), ("1000-3000", "1000–3000"), (">3000", "more than 3000")],
        "a_oktat": "Have you taught prosthodontics?",
        "a_oktat_opts": [("igen", "yes, currently"), ("nem", "no"), ("korabban", "in the past")],
        "a_tevekenyseg": "Where do you mainly work?",
        "a_tevekenyseg_opts": [("egyetemi", "university clinic"), ("maganpraxis", "private practice"), ("mindketto", "both"), ("egyeb", "elsewhere")],
        "b_eyebrow": "In general", "b_h2": "A few general questions",
        "b_note": "A denture is successful if the patient still wears it after six months, can eat with it, has no serious complaints, and is satisfied with it.",
        "b1": "In your experience, of 100 average patients needing a complete denture, how many will have a successful denture? *",
        "b1_unit": "patients in a hundred",
        "b2": "How much does success depend on the anatomy of the jaws? *",
        "b2_help": "The rest depends on the workmanship, the patient's adaptation and other factors. What percentage would you give to the anatomy?",
        "b2_unit": "% (0: not at all, 100: entirely)",
        "b3": "Which jaw's features matter more?",
        "b3_opts": [("felso", "the upper"), ("also", "the lower"), ("egyforman", "equally")],
        "b3_ratio": "If one matters more: roughly how many times as much?",
        "b4": "Is there any feature for which you would not recommend a conventional complete denture at all, but an implant-retained overdenture?",
        "b5": "How much does it matter whether the patient has had a complete denture before?",
        "b5_opts": [("alig", "hardly"), ("kozepesen", "moderately"), ("erosen", "a lot")],
        "b5_ph": "comment, if any",
        "items_h2": "The anatomical features",
        "items_instruction": "We always describe two variants, A and B. Mark the one with which, in your view, the denture starts with worse prospects. The “hundred patients” and “how sure” questions always refer to the variant you marked as worse.",
        "item_how": "How we record it in the study:",
        "q_direction": "Which variant is worse for the success of the denture? *",
        "dir_A_small": "Variant A is worse", "dir_B_small": "Variant B is worse",
        "dir_opt_small": "Neither", "dir_opt": "the middle is best, both extremes are worse",
        "dir_none": "No real difference", "dir_dk": "Cannot judge",
        "q_certainty": "How sure are you? *",
        "certainty_help": "50 %: like tossing a coin · 90 %: nine times out of ten · 99 %: almost certain",
        "q_hundred": "A hundred patients",
        "hundred_help": "Imagine 100 patients with variant A and 100 patients with variant B, otherwise similar patients. How many will have a successful denture?",
        "variant_A": "Variant A", "variant_B": "Variant B", "hundred_unit": "successful in a hundred",
        "q_range": "How large could the difference between the two groups be?",
        "range_help": "How many patients in a hundred is the difference, at least and at most? Give limits outside which you would be very surprised.",
        "range_min": "at least", "range_max": "at most", "range_unit": "patients",
        "comment_label": "Comment (optional)",
        "d_eyebrow": "Finally", "d_h2": "Summary",
        "d1": "Which five features matter most for the success of the denture?", "d1_help": "Start with the most important.",
        "d2": "Which two features together are the worst? Why?",
        "d2_help": "We mean a pair where the two together are worse than the sum of the two separately.",
        "d3": "Is there a feature that can compensate for another, unfavourable feature? How?",
        "d4": "What did we leave out? Is there a feature we did not ask about but you consider important?",
        "d5": "Overall, how confident are you in your answers today? *",
        "d5_opts": [("1", "1 · very unsure"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5 · very confident")],
        "d6": "Anything else you would like to add",
        "submit_note": "After submission the answers can no longer be changed.",
        "submit_button": "Submit answers",
        "submit_incomplete": "The questionnaire cannot be submitted yet: please check the missing or invalid answers.",
        "done_title": "Thank you · PREDICT expert questionnaire",
        "done_eyebrow": "Submitted", "done_h1": "Thank you for your answers!",
        "done_lead": "Questionnaire {code} has been received{when}.",
        "done_p": "Your answers will be used pooled with those of the other colleagues in the PREDICT study. Thank you for your time and your experience!",
        "done_view": "View my answers", "done_home": "Back to the start page",
        "err_evek": "Years of making complete dentures", "err_fogsorok": "Number of complete dentures made",
        "err_b1": "Successful dentures out of 100 patients", "err_b2": "How much depends on the anatomy",
        "err_direction": "which variant is worse", "err_certainty": "how sure",
        "err_range": "the lower limit of the difference is above the upper limit", "err_d5": "Confidence in your answers",
    },
}
